services:
  next:
    image: ghcr.io/ryuji0128/seta-hp:latest 
    container_name: next_app
    ports:
      - "2999:3000"
    env_file:
      - ./next/.env
    environment:
      - DATABASE_URL=mysql://app_user:${MYSQL_PASSWORD:-app_pass}@mysql:3306/app_db
      # - NEXTAUTH_URL=https://setaseisakusyo.com
      - NEXTAUTH_TRUST_HOST=true
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: 512m

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_db}
      MYSQL_USER: ${MYSQL_USER:-app_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_pass}
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
    command: /bin/sh -c "envsubst '$$SERVER_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - next
